server:
  port: 8082

springdoc:
  swagger-ui.path: /swagger-ui.html

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  datasource:
    url: jdbc:h2:D:/H2/db/db02
    username: root
    password: syc123
    driverClassName: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      platform: h2
      mode: always
